// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvazudsuclojfbzmnfew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2YXp1ZHN1Y2xvamZiem1uZmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzMwNzgsImV4cCI6MjA2MzA0OTA3OH0.Kra-VasUglyTSUpPJgM-FjbJM0YX9aKDwU8rEsPY8Zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);